import {env} from 'cloudflare:workers';
import {initialConfig,validate} from '../../../lib/game-config';
const bindings=()=>env as unknown as {DB:D1Database;BUCKET:R2Bucket;ADMIN_USER:string;ADMIN_PASSWORD:string};
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
const publicJson=(v:unknown)=>{const r=json(v);r.headers.set('Access-Control-Allow-Origin','https://drsun111.github.io');return r};
async function digest(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function auth(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|; )duang_session=([^;]+)/)?.[1];if(!token)return false;return !!await bindings().DB.prepare('SELECT token FROM sessions WHERE token=? AND expires>?').bind(await digest(token),Date.now()).first()}
async function handle(req:Request){try{const {DB,BUCKET,ADMIN_USER,ADMIN_PASSWORD}=bindings();const p=new URL(req.url).pathname.slice(5);
if(req.method==='GET'&&p==='config'){const row=await DB.prepare('SELECT value,version FROM config WHERE id=?').bind('main').first<{value:string;version:number}>();return publicJson({config:row?JSON.parse(row.value):initialConfig,version:row?.version||0})}
if(req.method==='GET'&&p.startsWith('image/')){const key=p.slice(6);if(!/^[a-zA-Z0-9.-]+$/.test(key))return json({error:'图片不存在'},404);const o=await BUCKET.get(key);if(!o)return json({error:'图片不存在'},404);return new Response(o.body,{headers:{'Content-Type':o.httpMetadata?.contentType||'image/png','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}
if(req.method==='GET'&&p==='session')return json({authenticated:await auth(req)});
if(req.method==='POST'||req.method==='PUT'){if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'请求来源无效'},403)}
if(req.method==='POST'&&p==='login'){const ip=req.headers.get('cf-connecting-ip')||'local';const a=await DB.prepare('SELECT count,until FROM attempts WHERE ip=?').bind(ip).first<{count:number;until:number}>();if(a&&a.until>Date.now()&&a.count>=8)return json({error:'尝试次数过多，请 15 分钟后再试'},429);const body=await req.json() as {username:string;password:string};if(!ADMIN_PASSWORD)return json({error:'管理员账户尚未配置'},503);const expected=await digest(ADMIN_PASSWORD),actual=await digest(String(body.password||''));let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^actual.charCodeAt(i);if(body.username!==ADMIN_USER||diff){await DB.prepare('INSERT INTO attempts(ip,count,until) VALUES(?,?,?) ON CONFLICT(ip) DO UPDATE SET count=?,until=?').bind(ip,(a&&a.until>Date.now()?a.count:0)+1,Date.now()+900000,(a&&a.until>Date.now()?a.count:0)+1,Date.now()+900000).run();return json({error:'账号或密码不正确'},401)}const token=crypto.randomUUID()+crypto.randomUUID();await DB.batch([DB.prepare('INSERT INTO sessions(token,expires) VALUES(?,?)').bind(await digest(token),Date.now()+86400000),DB.prepare('DELETE FROM attempts WHERE ip=?').bind(ip),DB.prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now())]);const res=json({ok:true});res.headers.set('Set-Cookie',`duang_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=86400`);return res}
if(!await auth(req))return json({error:'请先登录管理员'},401);
if(req.method==='POST'&&p==='logout'){const token=req.headers.get('cookie')?.match(/duang_session=([^;]+)/)?.[1];if(token)await DB.prepare('DELETE FROM sessions WHERE token=?').bind(await digest(token)).run();const r=json({ok:true});r.headers.set('Set-Cookie','duang_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0');return r}
if(req.method==='PUT'&&p==='config'){const b=await req.json() as {config:typeof initialConfig;version:number};validate(b.config);if(b.version===0){const r=await DB.prepare('INSERT OR IGNORE INTO config(id,value,version) VALUES(?,?,1)').bind('main',JSON.stringify(b.config)).run();if(!r.meta.changes)return json({error:'配置已更新，请刷新后再编辑'},409)}else{const r=await DB.prepare('UPDATE config SET value=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(b.config),'main',b.version).run();if(!r.meta.changes)return json({error:'配置已更新，请刷新后再编辑'},409)}return json({ok:true,version:b.version+1})}
if(req.method==='POST'&&p==='upload'){const data=await req.arrayBuffer();if(data.byteLength>3*1024*1024)return json({error:'图片不超过 3 MB'},413);const h=new Uint8Array(data);let type='',ext='';if(h[0]===137&&h[1]===80&&h[2]===78&&h[3]===71){type='image/png';ext='png'}else if(h[0]===255&&h[1]===216&&h[2]===255){type='image/jpeg';ext='jpg'}else if(new TextDecoder().decode(h.slice(0,4))==='RIFF'&&new TextDecoder().decode(h.slice(8,12))==='WEBP'){type='image/webp';ext='webp'}if(!type)return json({error:'只支持 PNG、JPG、WebP 图片'},400);const key=crypto.randomUUID()+'.'+ext;await BUCKET.put(key,data,{httpMetadata:{contentType:type}});return json({url:'/api/image/'+key})}
return json({error:'接口不存在'},404)}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'服务暂不可用，请稍后重试'},500)}}
export const GET=handle;export const POST=handle;export const PUT=handle;
