'use client';
import {useEffect,useRef,useState} from 'react';
import {Settings2,Volume2,VolumeX,RotateCcw,Pause,Play,ArrowUp,ArrowDown,Plus,Trash2,Upload,Save,LogOut,X,Sparkles} from 'lucide-react';
import {effects,GameConfig,initialConfig,Tier} from '../lib/game-config';
import {MergeEngine} from '../lib/engine';
const CLOUD_ORIGIN='https://duang-merge-studio.kasun11.chatgpt.site';
const isGithub=()=>typeof window!=='undefined'&&window.location.hostname==='drsun111.github.io';
async function api(path:string,method='GET',data?:unknown){const r=await fetch((isGithub()?CLOUD_ORIGIN:'')+'/api/'+path,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const b=await r.json() as {error?:string;config:GameConfig;version:number;authenticated:boolean;url:string};if(!r.ok)throw Error(b.error||'操作失败');if(path==='config'&&isGithub())b.config.tiers=b.config.tiers.map(t=>({...t,image:t.image?CLOUD_ORIGIN+t.image:''}));return b}
function Portrait({t}:{t:Tier}){return t.image?<img src={t.image} alt={t.name}/>:<span>{t.emoji}</span>}
export default function Home(){const [config,setConfig]=useState<GameConfig>(initialConfig),[draft,setDraft]=useState<GameConfig>(initialConfig),[version,setVersion]=useState(0),[loaded,setLoaded]=useState(false),[admin,setAdmin]=useState(false),[auth,setAuth]=useState(false),[username,setUsername]=useState('李泽萱'),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[score,setScore]=useState(0),[next,setNext]=useState(0),[over,setOver]=useState(false),[muted,setMuted]=useState(false),[paused,setPaused]=useState(false),[best,setBest]=useState(0),[preview,setPreview]=useState(-1);const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<MergeEngine|null>(null),touchX=useRef(210),adminRef=useRef(admin);adminRef.current=admin;
useEffect(()=>{if(new URLSearchParams(location.search).has('admin'))void openAdmin();api('config').then(b=>{setConfig(b.config);setDraft(b.config);setVersion(b.version);setLoaded(true)}).catch(e=>setNotice('配置加载失败：'+e.message));try{setBest(Number(localStorage.getItem('duang-best')||0))}catch{}},[]);
useEffect(()=>{if(!canvas.current||!loaded)return;const e=new MergeEngine(canvas.current,config,(s,n,o)=>{setScore(s);setNext(n);setOver(o)});engine.current=e;e.sound=!muted;e.paused=paused||adminRef.current;const key=(ev:KeyboardEvent)=>{if(adminRef.current||['INPUT','TEXTAREA','SELECT'].includes((ev.target as HTMLElement).tagName))return;if(ev.code==='Space'){ev.preventDefault();e.drop()}if(ev.code==='ArrowLeft'){ev.preventDefault();e.aim=Math.max(30,e.aim-15)}if(ev.code==='ArrowRight'){ev.preventDefault();e.aim=Math.min(390,e.aim+15)}if(ev.code==='KeyR')e.reset()};window.addEventListener('keydown',key);return()=>{e.destroy();window.removeEventListener('keydown',key)}},[config,loaded]);
useEffect(()=>{if(engine.current)engine.current.paused=paused||admin},[admin,paused]);
useEffect(()=>{if(score>best){setBest(score);try{localStorage.setItem('duang-best',String(score))}catch{}}},[score,best]);
function point(e:React.PointerEvent){const r=e.currentTarget.getBoundingClientRect();touchX.current=(e.clientX-r.left)/r.width*420;if(engine.current)engine.current.aim=touchX.current}
function patch(i:number,k:keyof Tier,v:string|number){setDraft(d=>({...d,tiers:d.tiers.map((t,j)=>j===i?{...t,[k]:v}:t)}))}
async function openAdmin(){if(isGithub()){window.location.href=CLOUD_ORIGIN+'/?admin=1';return}setAdmin(true);setNotice('');try{setAuth((await api('session')).authenticated)}catch(e){setNotice(String(e))}}
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice('');try{await api('login','POST',{username,password});setPassword('');setAuth(true)}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
async function upload(i:number,file?:File){if(!file)return;setBusy(true);setNotice('');try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('请选择 PNG、JPG 或 WebP 图片');const image=await createImageBitmap(file);const c=document.createElement('canvas');const ratio=Math.min(1,700/Math.max(image.width,image.height));c.width=Math.max(1,Math.round(image.width*ratio));c.height=Math.max(1,Math.round(image.height*ratio));c.getContext('2d')!.drawImage(image,0,0,c.width,c.height);image.close();const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('图片处理失败')),'image/png'));const r=await fetch('/api/upload',{method:'POST',body:blob});const b=await r.json() as {error?:string;config:GameConfig;version:number;authenticated:boolean;url:string};if(!r.ok)throw Error(b.error);patch(i,'image',b.url);setNotice('图片已上传，保存发布后对所有玩家生效')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
function move(i:number,d:number){setDraft(v=>{const tiers=[...v.tiers];[tiers[i],tiers[i+d]]=[tiers[i+d],tiers[i]];return {...v,tiers}})}
async function save(){setBusy(true);setNotice('');try{const b=await api('config','PUT',{config:draft,version});setVersion(b.version);setConfig(structuredClone(draft));setNotice('已发布。所有玩家重新打开游戏即可使用新配置。')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
function showPreview(i:number){setPreview(i)}
return <main><header><a className="brand" href="./"><span className="brand-icon">D<span>✦</span></span><div><strong>{config.title}</strong><small>MERGE & MAKE</small></div></a><button className="quiet" onClick={openAdmin}><Settings2 size={17}/><span>创作后台</span></button></header><div className="workspace"><aside className="left"><div className="eyebrow">YOUR OWN MERGE WORLD</div><h1>碰一下，<br/>大一点<span className="purple">。</span></h1><p>相同的角色相遇，<br/>下一位惊喜就诞生了。</p><div className="score-card"><span>本局得分</span><strong>{score.toString().padStart(3,'0')}</strong><div>个人最佳 <b>{best}</b></div></div><div className="tip"><Sparkles size={20}/><div><b>每次合成，都有一点不同</b><p>Duang 回弹 · 磁力 · 闪电 · 爱心<br/>在创作后台定义你的合成世界。</p></div></div></aside><section className="board-wrap"><div className="board-head"><span className="pill">自由合成</span><div className="next">下一个 <div><Portrait t={config.tiers[next]||config.tiers[0]}/></div></div></div><div className="board"><canvas ref={canvas} aria-label="合成游戏，鼠标点击或触摸松手投放，空格投放" onPointerMove={point} onPointerDown={e=>{point(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{point(e);engine.current?.drop()}}/>{!loaded&&<div className="game-overlay"><p>正在加载你的合成世界…</p>{notice&&<><p>{notice}</p><button onClick={()=>location.reload()}>重新加载</button></>}</div>}{over&&<div className="game-overlay"><span>✨</span><h2>这局合得很精彩</h2><p>本局得分 {score}</p><button onClick={()=>engine.current?.reset()}>再来一局</button></div>}</div><div className="controls"><button onClick={()=>{if(engine.current){engine.current.paused=!paused;setPaused(!paused)}}}>{paused?<Play size={18}/>:<Pause size={18}/>}<span>{paused?'继续':'暂停'}</span></button><button onClick={()=>{if(engine.current)engine.current.sound=muted;setMuted(!muted)}}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}<span>音效</span></button><button onClick={()=>{engine.current?.reset();setPaused(false)}}><RotateCcw size={18}/><span>重开</span></button></div><p className="hint">移动瞄准 · 点击投放 / 手机拖动后松手</p></section><aside className="right"><div className="section-heading"><h2>合成图鉴</h2><span>{config.tiers.length} 阶</span></div><div className="tier-list">{config.tiers.map((t,i)=><div className="tier-item" key={t.id}><span className="tier-no">{String(i+1).padStart(2,'0')}</span><div className="portrait"><Portrait t={t}/></div><div><b>{t.name}</b><small>{i===0?'初始角色':t.effect}</small></div>{i===config.tiers.length-1&&<span className="final-tag">终阶</span>}</div>)}</div><div className="how"><b>玩法小提示</b><p>两个相同角色碰撞后升级。<br/>堆叠超过警戒线 2 秒，本局结束。<br/>两个终阶相遇，会消除并获得奖励。</p></div></aside></div><footer>你的图片，你的合成宇宙。 <span>DUANG STUDIO</span></footer>
{admin&&<div className="modal-backdrop"><section className={'admin-modal '+(auth?'wide':'')}><div className="modal-head"><div><div className="eyebrow">DUANG STUDIO</div><h2>{auth?'创作后台':'管理员登录'}</h2></div><button className="icon-button" aria-label="关闭后台" onClick={()=>setAdmin(false)}><X/></button></div>{!auth?<form onSubmit={login}><label>管理员账号<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary full" disabled={busy}>{busy?'登录中…':'登录后台'}</button><p className="form-help">管理图片、合成顺序和每一级的专属特效。</p></form>:<><div className="admin-toolbar"><label>游戏名称<input value={draft.title} maxLength={40} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></label><label>Duang 弹性 <b>{draft.duang.toFixed(1)}</b><input type="range" min="0" max="2" step="0.1" value={draft.duang} onChange={e=>setDraft(d=>({...d,duang:Number(e.target.value)}))}/></label><button className="quiet" onClick={async()=>{await api('logout','POST');setAuth(false)}}><LogOut size={16}/>退出</button></div><p className="form-help">从上到下依次合成。该级特效会在合成出这张图片时出现，推荐透明背景 PNG。</p><div className="editor-list">{draft.tiers.map((t,i)=><div className="editor-row" key={t.id}><b className="row-no">{i+1}</b><label className="upload-tile"><Portrait t={t}/><span><Upload size={12}/>换图</span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(i,e.target.files?.[0])}/></label><div className="tier-fields"><label>角色名称<input value={t.name} maxLength={30} onChange={e=>patch(i,'name',e.target.value)}/></label><label>合成特效<select value={t.effect} onChange={e=>patch(i,'effect',e.target.value)}>{effects.map(f=><option key={f}>{f}</option>)}</select></label><label>大小 {t.radius}px<input type="range" min="15" max="85" value={t.radius} onChange={e=>patch(i,'radius',Number(e.target.value))}/></label></div><div className="row-actions"><button disabled={i===0} aria-label="上移" onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button disabled={i===draft.tiers.length-1} aria-label="下移" onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button onClick={()=>showPreview(i===0?0:i-1)} title="预览合成特效"><Play size={16}/></button><button disabled={draft.tiers.length<=2} aria-label="删除层级" onClick={()=>setDraft(d=>({...d,tiers:d.tiers.filter((_,j)=>i!==j)}))}><Trash2 size={16}/></button></div></div>)}</div><div className="admin-bottom"><button className="quiet" disabled={draft.tiers.length>=16} onClick={()=>setDraft(d=>({...d,tiers:[...d.tiers,{id:crypto.randomUUID(),name:'新角色',emoji:'⭐',image:'',radius:Math.min(85,20+d.tiers.length*5),effect:'星光爆发'}]}))}><Plus size={16}/>添加层级</button><button className="primary" disabled={busy} onClick={save}><Save size={16}/>{busy?'处理中…':'保存并发布'}</button></div></>}{notice&&<div role="status" className="notice">{notice}</div>}</section></div>}
{preview>=0&&<Preview config={draft} tier={preview} close={()=>setPreview(-1)}/>}
</main>}
function Preview({config,tier,close}:{config:GameConfig;tier:number;close:()=>void}){const ref=useRef<HTMLCanvasElement>(null),eng=useRef<MergeEngine|null>(null);useEffect(()=>{if(!ref.current)return;const e=new MergeEngine(ref.current,config,()=>{});e.sound=false;e.preview(tier);eng.current=e;return()=>e.destroy()},[config,tier]);return <div className="modal-backdrop preview-backdrop"><section className="preview-modal"><div className="modal-head"><h2>合成效果预览</h2><button className="icon-button" onClick={close} aria-label="关闭预览"><X/></button></div><p>{config.tiers[tier].name} × 2 → {config.tiers[Math.min(tier+1,config.tiers.length-1)].name}</p><canvas ref={ref}/><button className="primary full" onClick={()=>eng.current?.preview(tier)}>再看一次</button></section></div>}
