import {GameConfig} from './game-config';
type Ball={x:number;y:number;vx:number;vy:number;r:number;t:number;birth:number;sq:number;sv:number;angle:number;age:number};
type FX={x:number;y:number;t:number;age:number;kind:string;seed:number};
export class MergeEngine{
 c:CanvasRenderingContext2D; balls:Ball[]=[]; fx:FX[]=[]; images:HTMLImageElement[]=[];score=0;aim=210;next=0;over=false;paused=false;sound=true;lastDrop=-10;time=0;danger=0;destroyed=false;raf=0;audio?:AudioContext; accumulator=0;last=0;
 constructor(public canvas:HTMLCanvasElement,public config:GameConfig,public onState:(score:number,next:number,over:boolean,danger:number)=>void){this.c=canvas.getContext('2d')!;canvas.width=840;canvas.height=1400;this.config.tiers.forEach(t=>{const im=new Image();im.src=t.image;this.images.push(im)});this.pick();this.loop=this.loop.bind(this);this.raf=requestAnimationFrame(this.loop)}
 pick(){this.next=Math.floor(Math.random()*Math.min(3,this.config.tiers.length-1));this.onState(this.score,this.next,this.over,this.danger)}
 add(x:number,y:number,t:number){const b={x,y,vx:0,vy:0,r:this.config.tiers[t].radius,t,birth:this.time,sq:0,sv:0,angle:0,age:0};this.balls.push(b);return b}
 drop(){if(this.over||this.paused||this.time-this.lastDrop<.35)return;this.lastDrop=this.time;const r=this.config.tiers[this.next].radius;this.add(Math.max(r+10,Math.min(410-r,this.aim)),68,this.next);this.pick()}
 reset(){this.balls=[];this.fx=[];this.score=0;this.danger=0;this.over=false;this.paused=false;this.pick()}
 impact(b:Ball,s:number){b.sv=Math.max(b.sv,Math.min(5,s/180)*this.config.duang)}
 merge(a:Ball,b:Ball){const t=Math.min(a.t+1,this.config.tiers.length-1),x=(a.x+b.x)/2,y=(a.y+b.y)/2;this.balls=this.balls.filter(v=>v!==a&&v!==b);if(a.t<this.config.tiers.length-1){const n=this.add(x,y,t);n.vx=(a.vx+b.vx)/2;n.vy=-95;n.sv=6*this.config.duang;n.x=Math.max(n.r+10,Math.min(410-n.r,n.x));n.y=Math.min(685-n.r,n.y)}this.score+=a.t===this.config.tiers.length-1?500:(t+1)*10;this.fx.push({x,y,t,age:0,kind:this.config.tiers[t].effect,seed:Math.random()*6});if(this.sound)this.beep(t);this.onState(this.score,this.next,this.over,this.danger)}
 beep(t:number){try{this.audio??=new AudioContext();void this.audio.resume();const o=this.audio.createOscillator(),g=this.audio.createGain();o.type='sine';o.frequency.setValueAtTime(220+t*75,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(120+t*45,this.audio.currentTime+.2);g.gain.setValueAtTime(.11,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+.22);o.connect(g);g.connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+.23)}catch{}}
 step(dt:number){this.time+=dt;if(this.paused||this.over)return;for(const b of this.balls){b.age+=dt;b.vy+=2000*dt;b.vx*=.999;b.x+=b.vx*dt;b.y+=b.vy*dt;b.sv+=(-100*b.sq-9*b.sv)*dt;b.sq+=b.sv*dt;b.angle+=b.vx*dt/(b.r*8)}
 for(let it=0;it<7;it++){for(const b of this.balls){if(b.y+b.r>685){b.y=685-b.r;if(b.vy>0){this.impact(b,b.vy);b.vy*=-.12;b.vx*=.94}}if(b.x-b.r<10){b.x=b.r+10;b.vx=Math.abs(b.vx)*.2}if(b.x+b.r>410){b.x=410-b.r;b.vx=-Math.abs(b.vx)*.2}}
 let merged=false;for(let i=0;i<this.balls.length;i++){if(merged)break;for(let j=i+1;j<this.balls.length;j++){const a=this.balls[i],b=this.balls[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d>min+5){if(this.config.tiers[Math.min(a.t+1,this.config.tiers.length-1)].effect==='磁力相吸'&&a.t===b.t&&d<min+45&&d>0){const f=700/d;a.vx+=dx*f*dt;b.vx-=dx*f*dt}continue}if(d>min)continue;if(a.t===b.t&&a.age>.12&&b.age>.12){this.merge(a,b);merged=true;break}const nx=d>0?dx/d:1,ny=d>0?dy/d:0,wa=b.r*b.r/(a.r*a.r+b.r*b.r),wb=1-wa,penetration=min-d;a.x-=nx*penetration*wa;a.y-=ny*penetration*wa;b.x+=nx*penetration*wb;b.y+=ny*penetration*wb;const v=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(v<0){a.vx+=nx*v*wa*1.12;a.vy+=ny*v*wa*1.12;b.vx-=nx*v*wb*1.12;b.vy-=ny*v*wb*1.12;if(it===0){this.impact(a,-v);this.impact(b,-v)}}}}}
 for(const b of this.balls){b.x=Math.max(b.r+10,Math.min(410-b.r,b.x));b.y=Math.min(685-b.r,b.y)}
 const high=this.balls.some(b=>b.y-b.r<142&&b.age>1.2&&Math.abs(b.vy)<100);this.danger=high?this.danger+dt:Math.max(0,this.danger-dt*3);if(this.danger>2){this.over=true;this.onState(this.score,this.next,true,this.danger)}for(const f of this.fx)f.age+=dt;this.fx=this.fx.filter(f=>f.age<1.2)}
 drawBall(x:number,y:number,r:number,t:number,sq=0,angle=0,birth=10){const c=this.c,im=this.images[t];c.save();c.translate(x,y);c.rotate(angle);const k=Math.max(-.24,Math.min(.38,sq)),pop=birth<.65?1+.18*Math.exp(-birth*6)*Math.sin(birth*24):1;c.scale((1+k)*pop,(1-k*.8)*pop);c.shadowColor='#15286425';c.shadowBlur=8;c.shadowOffsetY=5;if(im?.complete&&im.naturalWidth){const size=r*2;const ratio=Math.min(size/im.naturalWidth,size/im.naturalHeight);c.drawImage(im,-im.naturalWidth*ratio/2,-im.naturalHeight*ratio/2,im.naturalWidth*ratio,im.naturalHeight*ratio)}else{c.font=`${r*1.65}px "Apple Color Emoji","Segoe UI Emoji",sans-serif`;c.textAlign='center';c.textBaseline='middle';c.fillText(this.config.tiers[t].emoji,0,2)}c.restore()}
 draw(){const c=this.c;c.setTransform(2,0,0,2,0,0);c.clearRect(0,0,420,700);for(let x=24;x<420;x+=28)for(let y=24;y<700;y+=28){c.fillStyle='#ccdaf033';c.beginPath();c.arc(x,y,1,0,Math.PI*2);c.fill()}c.save();c.setLineDash([5,7]);c.strokeStyle=this.danger>.1?'#ef476f':'#c5cde0';c.beginPath();c.moveTo(10,142);c.lineTo(410,142);c.stroke();c.restore();c.font='11px sans-serif';c.fillStyle='#9aa5bd';c.fillText('警戒线',18,134);if(!this.over){const r=this.config.tiers[this.next].radius,x=Math.max(10+r,Math.min(410-r,this.aim));c.save();c.setLineDash([3,8]);c.strokeStyle='#acb4fa';c.beginPath();c.moveTo(x,90);c.lineTo(x,660);c.stroke();c.restore();this.drawBall(x,68,r,this.next)}for(const b of this.balls)this.drawBall(b.x,b.y,b.r,b.t,b.sq,b.angle,this.time-b.birth);for(const f of this.fx){const u=f.age;c.save();c.globalAlpha=Math.max(0,1-u/1.2);c.translate(f.x,f.y);if(f.kind==='闪电'){c.strokeStyle='#8062ff';c.lineWidth=3;for(let i=0;i<8;i++){c.save();c.rotate(i*Math.PI/4+f.seed);c.beginPath();c.moveTo(0,0);c.lineTo(15+u*20,-10);c.lineTo(12+u*35,4);c.lineTo(32+u*90,0);c.stroke();c.restore()}}else if(f.kind==='磁力相吸'){c.strokeStyle='#07bfc2';c.lineWidth=2;for(let j=0;j<3;j++){c.beginPath();c.ellipse(0,0,20+u*90+j*10,8+u*35+j*8,u*3,0,Math.PI*2);c.stroke()}}else if(f.kind!=='无特效'){for(let i=0;i<12;i++){const a=i*Math.PI/6+f.seed,rad=20+u*100;c.fillStyle=f.kind==='爱心氛围'?'#ff5795':'#ffbd38';c.font=`${22-u*8}px sans-serif`;c.textAlign='center';c.fillText(f.kind==='爱心氛围'?'♥':f.kind==='星光爆发'?'✦':'·',Math.cos(a)*rad,Math.sin(a)*rad-u*25)}}c.fillStyle='#5344d6';c.font='bold 20px sans-serif';c.textAlign='center';c.fillText('+'+((f.t+1)*10),0,-35-u*50);c.restore()}if(this.paused){c.fillStyle='#ffffffbb';c.fillRect(0,0,420,700);c.fillStyle='#5145cc';c.font='bold 26px sans-serif';c.textAlign='center';c.fillText('已暂停',210,350)}}
 loop(ts:number){if(this.destroyed)return;const dt=this.last?Math.min((ts-this.last)/1000,.05):0;this.last=ts;this.accumulator+=dt;while(this.accumulator>=1/120){this.step(1/120);this.accumulator-=1/120}this.draw();this.raf=requestAnimationFrame(this.loop)}
 preview(t:number){this.reset();this.add(145,420,t);this.add(275,420,t);this.balls[0].vx=150;this.balls[1].vx=-150}
 destroy(){this.destroyed=true;cancelAnimationFrame(this.raf);void this.audio?.close()}
}
